
// This file has been generated by the GUI designer. Do not modify.
namespace Xavalon.XamlStyler.XamarinStudio.Gui
{
	public partial class MainWidget
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.Label description;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Xavalon.XamlStyler.XamarinStudio.Gui.MainWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Xavalon.XamlStyler.XamarinStudio.Gui.MainWidget";
			// Container child Xavalon.XamlStyler.XamarinStudio.Gui.MainWidget.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.description = new global::Gtk.Label();
			this.description.Name = "description";
			this.description.Xpad = 10;
			this.description.Ypad = 10;
			this.description.Xalign = 0F;
			this.description.Yalign = 0F;
			this.description.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.description.Wrap = true;
			this.alignment1.Add(this.description);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
