
// This file has been generated by the GUI designer. Do not modify.
namespace Xavalon.XamlStyler.XamarinStudio.Gui
{
	public partial class MainOptions
	{
		private global::Gtk.Button button22;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Xavalon.XamlStyler.XamarinStudio.Gui.MainOptions
			this.Name = "Xavalon.XamlStyler.XamarinStudio.Gui.MainOptions";
			this.Title = global::Mono.Unix.Catalog.GetString("dialog1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Xavalon.XamlStyler.XamarinStudio.Gui.MainOptions.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Internal child Xavalon.XamlStyler.XamarinStudio.Gui.MainOptions.ActionArea
			global::Gtk.HButtonBox w2 = this.ActionArea;
			w2.Name = "dialog1_ActionArea";
			w2.Spacing = 10;
			w2.BorderWidth = ((uint)(5));
			w2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button22 = new global::Gtk.Button();
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			this.button22.UseUnderline = true;
			this.button22.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.AddActionWidget(this.button22, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w2[this.button22]));
			w3.Expand = false;
			w3.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
